application: moneyland-su
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /css
  static_dir: css
  
- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images
    
- url: /.*
  script: main.py