from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns("",
					   (r"^test/*$", "dvk.main.views.test"),
					   (r"^uf$", "dvk.main.views.formuser"),
					   (r"^form/(?P<newId>\d*)$", "dvk.main.views.form"),
					   (r"^tree/(?P<kurator>\d*)$", "dvk.main.views.tree"),

					   (r"^.*_eng.html$", "dvk.main.views.eng"),
					   (r"^$", "dvk.main.views.index"),
					   (r"^r(?P<refurl>\d+)$", "dvk.main.views.index"),
					   (r"^index.html$", "dvk.main.views.index"),
					   (r"^logout/$", "dvk.main.views.logout_view"),
					   (r"^registration.html$", "dvk.main.views.register"),
					   (r"^restorepassword.html$", "dvk.main.views.restorepassword"),
					   (r"^new/(?P<id>\d+)$", "dvk.main.views.news"),
					   (r"^(?P<name>[\w\-_]+).html$", "dvk.main.views.pages"),
					   (r"^user/profile.html$", "dvk.main.views.user_profile"),
					   (r"^user/profile.html/(?P<success>success)$", "dvk.main.views.user_profile"),
					   (r"^user/status.html$", "dvk.main.views.user_status"),
					   (r"^user/partners.html$", "dvk.main.views.user_partners"),
					   (r"^user/books1.html$", "dvk.main.views.user_books1"),
					   (r"^user/books2.html$", "dvk.main.views.user_books2"),
					   (r"^user/ajax/order.html$", "dvk.main.views.user_order"),
					   (r"^user/order.html$", "dvk.main.views.user_order"),
					   (r"^user/order.html/(?P<image>\d+)$", "dvk.main.views.user_order"),
					   (r"^user/partner/(?P<member>\d+)$", "dvk.main.views.user_partners"),
					   (r"^user/delete/(?P<partnerId>\d+)$", "dvk.main.views.user_delete_partner"),
					   (r"^user/mail.html$", "dvk.main.views.user_mail"),
					   (r"^user/activate/(?P<level>\d*)$", "dvk.main.views.user_activate"),
					   (r"^user/activated/(?P<level>\d*)$", "dvk.main.views.user_activated"),
					   (r"^user/mail/$", "dvk.main.views.user_mail"),
					   (r"^user/news/*$", "dvk.main.views.user_news"),
					   (r"^user/mail/id(?P<id>\d+)$", "dvk.main.views.user_mail_show"),
					   (r"^user/mail/out/*$", "dvk.main.views.user_mail_out"),
					   (r"^user/sentmail/(?P<id>\d*)$", "dvk.main.views.user_sentmail"),
					   (r"^user/(?P<page>\w+).html$", "dvk.main.views.user"),
					   (r"^user/$", "dvk.main.views.user_status"),
					   (r"^tasks/summary/$", "dvk.main.views.tasks_summary"),
					   (r"^admin/edit/(?P<userId>\d+)$", "dvk.main.views.adminEdit"),
					   (r"^admin/(?P<key>\w*)$", "dvk.main.views.admin"),
					   (r"^flush/*$", "dvk.main.views.flush"),
					   (r"^blob/(?P<id>\d*)$", "dvk.main.views.blob"),
					   #cron jobs update main stat
					   (r"^cronjobs$", "dvk.main.views.cron_jobs"),
					   
					   #(r"^.*$", "dvk.main.views.eng"),
					   )